config/routes.rb
Rails.application.routes.draw do
  get "/pets", to: "pets#index"
  get "/pets/new", to: "pets#new"

  get "/pets/:id", to: "pets#show", as: :pet
  post "/pets", to: "pets#create"

  delete "/pets/:id", to: "pets#destroy"

  get "/pets/:id/edit", to: "pets#edit", as: :edit_pet
  patch "/pets/:id", to: "pets#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = %w(dog cat bird horse)
  validates :name, presence: true
  validates :species, inclusion: { in: SPECIES }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render 'edit'
    end
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end

  def set_pet
    @pet = Pet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container my-5">
      <div class="row">
        <div class="col">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pets/_form.html.erb
<!-- <%#= form_for @pet do |f| %>
  <div class="form-group">
    <%#= f.label :name %>
    <%#= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%#= f.label :address %>
    <%#= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%#= f.label :species %>
    <%#= f.select :species, collection: Pet::SPECIES, class: "form-control" %>
  </div>

  <div class="form-group">
    <%#= f.label :found_on %>
    <%#= f.date_field :found_on, class: "form-control" %>
  </div>

  <div class="form-group">
    <%#= f.submit class: "btn btn-primary" %>
  </div>
<%# end %> -->

<%= simple_form_for @pet do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :species, collection: Pet::SPECIES %>
  <%= f.input :found_on %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/pets/edit.html.erb
<h1>Edit <%= @pet.name %></h1>

<%= render "form" %>

app/views/pets/index.html.erb
<h1>All pets</h1>

<ul>
  <% @pets.each do |pet| %>
    <li><%= link_to pet.name, pet_path(pet) %></li>
  <% end %>
</ul>

<%= link_to "Add a pet", pets_new_path %>

app/views/pets/new.html.erb
<h1>Add a new pet</h1>

<%= render "form" %>

app/views/pets/show.html.erb
<h1><%= @pet.name %> <small>(<%= @pet.species %>)</small></h1>
<ul>
  <li>Address: <%= @pet.address %></li>
  <li>Found on: <%= @pet.found_on %></li>
</ul>

<%= link_to "Edit #{@pet.name}", edit_pet_path(@pet) %>
<br>
<%= link_to "Delete #{@pet.name}", pet_path(@pet), method: :delete, data: { confirm: "Are your sure?"} %>
<br>
<%= link_to "Back to all pets", pets_path %>